# success values
# sql.h
SQL_INVALID_HANDLE		= -2
SQL_ERROR				= -1
SQL_SUCCESS				= 0
SQL_SUCCESS_WITH_INFO	= 1
SQL_STILL_EXECUTING		= 2
SQL_NEED_DATA			= 99
SQL_NO_DATA_FOUND		= 100

sql_errors = [SQL_ERROR, SQL_INVALID_HANDLE]

# sqlext.h
SQL_FETCH_NEXT		= 0x01
SQL_FETCH_FIRST		= 0x02
SQL_FETCH_LAST		= 0x04
SQL_FETCH_PRIOR		= 0x08
SQL_FETCH_ABSOLUTE	= 0x10
SQL_FETCH_RELATIVE	= 0x20
SQL_FETCH_RESUME	= 0x40
SQL_FETCH_BOOKMARK	= 0x80

# sql types
SQL_TYPE_NULL	= 0
SQL_CHAR		= 1
SQL_NUMERIC		= 2
SQL_DECIMAL		= 3
SQL_INTEGER		= 4
SQL_SMALLINT	= 5
SQL_FLOAT		= 6
SQL_REAL		= 7
SQL_DOUBLE		= 8
SQL_DATE		= 9
SQL_TIME		= 10
SQL_TIMESTAMP	= 11
SQL_VARCHAR		= 12

# SQL extended datatypes

SQL_LONGVARCHAR					= -1
SQL_BINARY						= -2
SQL_VARBINARY					= -3
SQL_LONGVARBINARY				= -4
SQL_BIGINT						= -5
SQL_TINYINT						= -6
SQL_BIT							= -7
SQL_INTERVAL_YEAR				= -80
SQL_INTERVAL_MONTH				= -81
SQL_INTERVAL_YEAR_TO_MONTH		= -82
SQL_INTERVAL_DAY				= -83
SQL_INTERVAL_HOUR				= -84
SQL_INTERVAL_MINUTE				= -85
SQL_INTERVAL_SECOND				= -86
SQL_INTERVAL_DAY_TO_HOUR		= -87
SQL_INTERVAL_DAY_TO_MINUTE		= -88
SQL_INTERVAL_DAY_TO_SECOND		= -89
SQL_INTERVAL_HOUR_TO_MINUTE		= -90
SQL_INTERVAL_HOUR_TO_SECOND		= -91
SQL_INTERVAL_MINUTE_TO_SECOND	= -92
SQL_UNICODE						= -95
SQL_UNICODE_VARCHAR				= -96
SQL_UNICODE_LONGVARCHAR			= -97
SQL_UNICODE_CHAR				= SQL_UNICODE
SQL_TYPE_DRIVER_START			= SQL_INTERVAL_YEAR
SQL_TYPE_DRIVER_END				= SQL_UNICODE_LONGVARCHAR
SQL_SIGNED_OFFSET				= -20
SQL_UNSIGNED_OFFSET				= -22

# Special length values (don't work yet)
SQL_NULL_DATA		= -1
SQL_DATA_AT_EXEC	= -2
SQL_NTS				= -3

# SQLGetInfo type types
STRING = 's'
INT16 = 'h'
INT32 = 'l'

# C datatype to SQL datatype mapping      SQL types 
SQL_C_CHAR    = SQL_CHAR             #  CHAR, VARCHAR, DECIMAL, NUMERIC
SQL_C_LONG    = SQL_INTEGER          #  INTEGER                      
SQL_C_SHORT   = SQL_SMALLINT         #  SMALLINT                     
SQL_C_FLOAT   = SQL_REAL             #  REAL                         
SQL_C_DOUBLE  = SQL_DOUBLE           #  FLOAT, DOUBLE                
SQL_C_DEFAULT = 99
#
SQL_C_DATE       = SQL_DATE
SQL_C_TIME       = SQL_TIME
SQL_C_TIMESTAMP  = SQL_TIMESTAMP
SQL_C_BINARY     = SQL_BINARY
SQL_C_BIT        = SQL_BIT
SQL_C_TINYINT    = SQL_TINYINT
SQL_C_SLONG      = SQL_C_LONG+SQL_SIGNED_OFFSET    #  SIGNED INTEGER   
SQL_C_SSHORT     = SQL_C_SHORT+SQL_SIGNED_OFFSET   #  SIGNED SMALLINT  
SQL_C_STINYINT   = SQL_TINYINT+SQL_SIGNED_OFFSET   #  SIGNED TINYINT   
SQL_C_ULONG      = SQL_C_LONG+SQL_UNSIGNED_OFFSET  #  UNSIGNED INTEGER 
SQL_C_USHORT     = SQL_C_SHORT+SQL_UNSIGNED_OFFSET #  UNSIGNED SMALLINT
SQL_C_UTINYINT   = SQL_TINYINT+SQL_UNSIGNED_OFFSET #  UNSIGNED TINYINT 
SQL_C_BOOKMARK   = SQL_C_ULONG                     #  BOOKMARK         

# from "sql.h"
# Defines for SQLGetInfo
SQL_ACTIVE_CONNECTIONS				= 0,	INT16
SQL_ACTIVE_STATEMENTS				= 1,	INT16
SQL_DATA_SOURCE_NAME				= 2,	STRING
SQL_DRIVER_HDBC						= 3,	INT32
SQL_DRIVER_HENV						= 4,	INT32
SQL_DRIVER_HSTMT					= 5,	INT32
SQL_DRIVER_NAME						= 6,	STRING
SQL_DRIVER_VER						= 7,	STRING
SQL_FETCH_DIRECTION					= 8,	INT32
SQL_ODBC_API_CONFORMANCE			= 9,	INT16
SQL_ODBC_VER						= 10,	STRING
SQL_ROW_UPDATES						= 11,	STRING
SQL_ODBC_SAG_CLI_CONFORMANCE		= 12,	INT16
SQL_SERVER_NAME						= 13,	STRING
SQL_SEARCH_PATTERN_ESCAPE			= 14,	STRING
SQL_ODBC_SQL_CONFORMANCE			= 15,	INT16
SQL_DATABASE_NAME					= 16,	STRING
SQL_DBMS_NAME						= 17,	STRING
SQL_DBMS_VER						= 18,	STRING
SQL_ACCESSIBLE_TABLES				= 19,	STRING
SQL_ACCESSIBLE_PROCEDURES			= 20,	STRING
SQL_PROCEDURES						= 21,	STRING
SQL_CONCAT_NULL_BEHAVIOR			= 22,	INT16
SQL_CURSOR_COMMIT_BEHAVIOR			= 23,	INT16
SQL_CURSOR_ROLLBACK_BEHAVIOR		= 24,	INT16
SQL_DATA_SOURCE_READ_ONLY			= 25,	STRING
SQL_DEFAULT_TXN_ISOLATION			= 26,	INT32
SQL_EXPRESSIONS_IN_ORDERBY			= 27,	STRING
SQL_IDENTIFIER_CASE					= 28,	INT16
SQL_IDENTIFIER_QUOTE_CHAR			= 29,	STRING
SQL_MAX_COLUMN_NAME_LEN				= 30,	INT16
SQL_MAX_CURSOR_NAME_LEN				= 31,	INT16
SQL_MAX_OWNER_NAME_LEN				= 32,	INT16
SQL_MAX_PROCEDURE_NAME_LEN			= 33,	INT16
SQL_MAX_QUALIFIER_NAME_LEN			= 34,	INT16
SQL_MAX_TABLE_NAME_LEN				= 35,	INT16
SQL_MULT_RESULT_SETS				= 36,	STRING
SQL_MULTIPLE_ACTIVE_TXN				= 37,	STRING
SQL_OUTER_JOINS						= 38,	STRING
SQL_OWNER_TERM						= 39,	STRING
SQL_PROCEDURE_TERM					= 40,	STRING
SQL_QUALIFIER_NAME_SEPARATOR		= 41,	STRING
SQL_QUALIFIER_TERM					= 42,	STRING
SQL_SCROLL_CONCURRENCY				= 43,	INT32
SQL_SCROLL_OPTIONS					= 44,	INT32
SQL_TABLE_TERM						= 45,	STRING
SQL_TXN_CAPABLE						= 46,	INT16
SQL_USER_NAME						= 47,	STRING
SQL_CONVERT_FUNCTIONS				= 48,	INT32
SQL_NUMERIC_FUNCTIONS				= 49,	INT32
SQL_STRING_FUNCTIONS				= 50,	INT32
SQL_SYSTEM_FUNCTIONS				= 51,	INT32
SQL_TIMEDATE_FUNCTIONS				= 52,	INT32
SQL_CONVERT_BIGINT					= 53,	INT32
SQL_CONVERT_BINARY					= 54,	INT32
SQL_CONVERT_BIT						= 55,	INT32
SQL_CONVERT_CHAR					= 56,	INT32
SQL_CONVERT_DATE					= 57,	INT32
SQL_CONVERT_DECIMAL					= 58,	INT32
SQL_CONVERT_DOUBLE					= 59,	INT32
SQL_CONVERT_FLOAT					= 60,	INT32
SQL_CONVERT_INTEGER					= 61,	INT32
SQL_CONVERT_LONGVARCHAR				= 62,	INT32
SQL_CONVERT_NUMERIC					= 63,	INT32
SQL_CONVERT_REAL					= 64,	INT32
SQL_CONVERT_SMALLINT				= 65,	INT32
SQL_CONVERT_TIME					= 66,	INT32
SQL_CONVERT_TIMESTAMP				= 67,	INT32
SQL_CONVERT_TINYINT					= 68,	INT32
SQL_CONVERT_VARBINARY				= 69,	INT32
SQL_CONVERT_VARCHAR					= 70,	INT32
SQL_CONVERT_LONGVARBINARY			= 71,	INT32
SQL_TXN_ISOLATION_OPTION			= 72,	INT32
SQL_ODBC_SQL_OPT_IEF				= 73,	STRING
SQL_CORRELATION_NAME				= 74,	INT16
SQL_NON_NULLABLE_COLUMNS			= 75,	INT16
SQL_DRIVER_HLIB						= 76,	INT32
SQL_DRIVER_ODBC_VER					= 77,	STRING
SQL_LOCK_TYPES						= 78,	INT32
SQL_POS_OPERATIONS					= 79,	INT32
SQL_POSITIONED_STATEMENTS			= 80,	INT32
SQL_GETDATA_EXTENSIONS				= 81,	INT32
SQL_BOOKMARK_PERSISTENCE			= 82,	INT32
SQL_STATIC_SENSITIVITY				= 83,	INT32
SQL_FILE_USAGE						= 84,	INT16
SQL_NULL_COLLATION					= 85,	INT16
SQL_ALTER_TABLE						= 86,	INT32
SQL_COLUMN_ALIAS					= 87,	STRING
SQL_GROUP_BY						= 88,	INT16
SQL_KEYWORDS						= 89,	STRING
SQL_ORDER_BY_COLUMNS_IN_SELECT		= 90,	STRING
SQL_OWNER_USAGE						= 91,	INT32
SQL_QUALIFIER_USAGE					= 92,	INT32
SQL_QUOTED_IDENTIFIER_CASE			= 93,	INT32
SQL_SPECIAL_CHARACTERS				= 94,	STRING
SQL_SUBQUERIES						= 95,	INT32
SQL_UNION							= 96,	INT32
SQL_MAX_COLUMNS_IN_GROUP_BY			= 97,	INT16
SQL_MAX_COLUMNS_IN_INDEX			= 98,	INT16
SQL_MAX_COLUMNS_IN_ORDER_BY			= 99,	INT16
SQL_MAX_COLUMNS_IN_SELECT			= 100,	INT16
SQL_MAX_COLUMNS_IN_TABLE			= 101,	INT16
SQL_MAX_INDEX_SIZE					= 102,	INT32
SQL_MAX_ROW_SIZE_INCLUDES_LONG		= 103,	STRING
SQL_MAX_ROW_SIZE					= 104,	INT32
SQL_MAX_STATEMENT_LEN				= 105,	INT32
SQL_MAX_TABLES_IN_SELECT			= 106,	INT16
SQL_MAX_USER_NAME_LEN				= 107,	INT16
SQL_MAX_CHAR_LITERAL_LEN			= 108,	INT32
SQL_TIMEDATE_ADD_INTERVALS			= 109,	INT32
SQL_TIMEDATE_DIFF_INTERVALS			= 110,	INT32
SQL_NEED_LONG_DATA_LEN				= 111,	STRING
SQL_MAX_BINARY_LITERAL_LEN			= 112,	INT32
SQL_LIKE_ESCAPE_CLAUSE				= 113,	STRING
SQL_QUALIFIER_LOCATION				= 114,	INT16
#
# <Phew!>
#
#  Level 1 Prototypes                            

# <sqlext.h>
#  Options for SQLDriverConnect 
SQL_DRIVER_NOPROMPT             = 0
SQL_DRIVER_COMPLETE             = 1
SQL_DRIVER_PROMPT               = 2
SQL_DRIVER_COMPLETE_REQUIRED    = 3

# For SQLGetFunctions
SQL_API_ALL_FUNCTIONS			= 0

# Defines for SQLBindParameter and
# SQLProcedureColumns (returned in the result set)
SQL_PARAM_TYPE_UNKNOWN           = 0
SQL_PARAM_INPUT                  = 1
SQL_PARAM_INPUT_OUTPUT           = 2
SQL_RESULT_COL                   = 3
SQL_PARAM_OUTPUT                 = 4
SQL_RETURN_VALUE                 = 5

#  SQLFreeStmt defines
SQL_CLOSE                       = 0
SQL_DROP                        = 1
SQL_UNBIND                      = 2
SQL_RESET_PARAMS                = 3

# 	Added by Edward Akerboom:

#	SQL Handles
SQL_HANDLE_ENV                  = 1
SQL_HANDLE_DBC                  = 2
SQL_HANDLE_STMT                 = 3
SQL_HANDLE_DESC                 = 4

# SQLGetEnvAttr - Attributes
SQL_ATTR_ODBC_VERSION           = 200
SQL_ATTR_CONNECTION_POOLING     = 201
SQL_ATTR_CP_MATCH               = 202


# SQLGetEnvAttr - SQL_ATTR_ODBC_VERSION
SQL_OV_ODBC2                    = 2, INT32
SQL_OV_ODBC3                    = 3, INT32

# # SQLGetEnvAttr - SQL_ATTR_CONNECTION_POOLING
# SQL_CP_OFF                              0UL
# SQL_CP_ONE_PER_DRIVER                   1UL
# SQL_CP_ONE_PER_HENV                     2UL
# SQL_CP_DEFAULT                          SQL_CP_OFF
#
#
# # SQLGetEnvAttr - SQL_ATTR_CP_MATCH
# SQL_CP_STRICT_MATCH                     0UL
# SQL_CP_RELAXED_MATCH                    1UL
# SQL_CP_MATCH_DEFAULT                    SQL_CP_STRICT_MATCH

SQL_NO_DATA                      = 100
SQL_NULL_HENV                    = 0
SQL_NULL_HDBC                    = 0
SQL_NULL_HSTMT                   = 0

# Don't know if this works:
SQL_IS_POINTER                   = -4
SQL_IS_UINTEGER                  = -5
SQL_IS_INTEGER                   = -6
SQL_IS_USMALLINT                 = -7
SQL_IS_SMALLINT                  = -8


